In [24]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Variance :", scaler.var_)
X_std = scaler.transform(X)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]


# [Problem 1] Enumeration of classes used so far

In [25]:
# Pandas
import pandas as pd
import inspect

classes = list(map(lambda x:x[0], inspect.getmembers(pd, inspect.isclass)))
classes[:5]

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame']

In [26]:
# matplotlib
import matplotlib
classes = list(map(lambda x:x[0], inspect.getmembers(matplotlib, inspect.isclass)))
classes[:5]

['ExecutableNotFoundError',
 'LooseVersion',
 'MatplotlibDeprecationWarning',
 'MutableMapping',
 'Parameter']

In [27]:
# Show all methods
dir(scaler)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_n_features',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_validate_data',
 'copy',
 'fit',
 'fit_transform',
 'get_params',
 'inverse_transform',
 'mean_',
 'n_features_in_',
 'n_samples_seen_',
 'partial_fit',
 'scale_',
 'set_params',
 'transform',
 'var_',
 'with_mean',
 'with_std']

# [Problem 2] Enumeration of methods and instance variables that have been used so far

Method:
* ndarray.sum()
* pandas.DataFrame.groupby()
* range()
* zip()
* matplotlib.pyplot.scatter

Instance variables
* ndarray.shape
* pandas.DataFrame.columns
* pandas.DataFrame.index
* ndarray.dtype
* ndarray.T

# [Problem 3] Creating a standardized class by scratch

In [28]:
class ScratchStandardScaler():
    """
    Class for standardization

    Attributes

    mean_: ndarray, shape (n_features,) of the following form
    average

    var_: ndarray, shape (n_features,) of the following form
    Distributed
    """
    def fit(self, X):
        """
        Calculate the mean and standard deviation for standardization.

        Parameters

        X: ndarray, shape (n_samples, n_features) of the following form
        Training data
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)
        
    def transform(self, X):
        """
       Standardize using the value obtained by fit.

        Parameters

        X: ndarray, shape (n_samples, n_features) of the following form
        Feature value

        Returns

        X_scaled: ndarray, shape (n_samples, n_features) of the following form
        Standardized special amount
        """
        # Explanatory variable-mean of that column / square root of standard deviation of each column
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [29]:
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean :", scratch_scaler.mean_)
print("Vanriance :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)
print(X_std)

print('X_std mean: {:.1f}, variance: {:.1f}'.format(X_std.mean(), X_std.var()))

Mean : [4.86 3.31 1.45 0.22]
Vanriance : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]
X_std mean: 0.0, variance: 1.0


In [30]:
# Compare with Standard library
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Vanriance :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)
print('X_std mean: {:.1f}, variance: {:.1f}'.format(X_std.mean(), X_std.var()))

Mean : [4.86 3.31 1.45 0.22]
Vanriance : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]
X_std mean: 0.0, variance: 1.0


# Problem 4] Creating a class that performs 4 arithmetic operations

In [31]:
class ArithmeticOperation():
    """
        A class that performs four arithmetic operations.
     Set the argument to the initial value.
     Please note that it will be updated after the calculation.
     Example)
     example = FourArithmeticOperations (5)
     example.add (3)
     ==> 8

     Parameters
     ----------
     value: float or int
         initial value

     Attributes
     ----------
     value: float or int
         Calculation result
    """
    def __init__(self, value):
        try:
            value+1
            self.value = value
            print("The initial value {} has been set".format(self.value))
        except TypeError:
            print('Invalid number')
    def add(self, value):
        """
        Add the received argument to self.value
        """
        try:
            value+1
            self.value += value
        except TypeError:
            print('Invalid number')
    def sub(self, value):
        """
        Subtract the received argument to self.value
        """
        try:
            value+1
            self.value -= value
        except TypeError:
            print('Invalid number')
    def mul(self, value):
        """
        Multiply the received argument to self.value
        """
        try:
            value+1
            self.value *= value
        except TypeError:
            print('Invalid number')
    def div(self, value):
        """
        Divide the received argument to self.value
        """
        try:
            value+1
            self.value /= value
        except TypeError:
            print('Invalid number')

example = ArithmeticOperation(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.sub(4)
print("value : {}".format(example.value))
example.mul(2)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))

The initial value 5 has been set
value : 5
value : 8
value : 4
value : 8
value : 2.6666666666666665
