In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

<h2>[Problem 1] Matrix product is calculated manually</h2>

<img src="1.jpg"/><br><br>

<h2>[Problem 2] Calculation by NumPy function</h2>

In [2]:
multiplied_matrix = a_ndarray@b_ndarray
print(multiplied_matrix)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h2>[Problem 3] Implementation of calculation of a certain element</h2>

In [3]:
sum_row_0 = 0
for column in range(3):
    sum_row_0 += a_ndarray[0][column] * b_ndarray[column][0]
print(sum_row_0)

6


<h2>[Problem 4] Creating a function that performs matrix multiplication</h2>

In [4]:
def matrix_mul_by_hand(A, B):
    """
    A function that returns matrix of ndarray of multiplication of 2 ndarray matrix (i.e. A.B).
    --------------
    A: ndarray 
        Matrix size m x n in type ndarray
    B: ndarray 
        Matrix size n x p in type ndarray
    Returns
    --------------
    multiplied_matrix_manually: ndarray
        The array after multiplication of 2 ndarray matrix.
    """
    # 4. A combination of matrices with undefined matrix products
    if not(isinstance(A, np.ndarray) & isinstance(B, np.ndarray)):
        print("Invalid type of array! Please use ndarray")
        return
    if (A.shape[1] != B.shape[0]):
        print("Invalid size of array! Please use correct size (A: m x n and B: n x p)")
        return
    multiplied_matrix_manually = np.array([])
    row_element = np.array([])
    row_array = np.array([])
    for row in range (A.shape[0]):
        for column1 in range(B.shape[1]):
            for column2 in range(A.shape[1]):
                row_element = np.append(row_element,A[row][column2] * B[column2][column1])
            row_array = np.append(row_array,np.sum(row_element))
            row_element = np.array([])
        multiplied_matrix_manually = np.append(multiplied_matrix_manually,row_array)
        #print(multiplied_matrix_manually)
        row_array = np.array([])
    multiplied_matrix_manually = multiplied_matrix_manually.reshape(A.shape[0], B.shape[1])
    return multiplied_matrix_manually

In [5]:
multiplied_matrix_manually = matrix_mul_by_hand(a_ndarray,b_ndarray)
print(multiplied_matrix_manually)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


<h2>[Problem 5] Judge the input whose calculation is not defined

I have already included it in my function above, which are print() function before calculating. I also include checking if user input wrong type of array.

In [6]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [7]:
# Raise the error and returned!
matrix_mul_by_hand(d_ndarray, e_ndarray)

Invalid size of array! Please use correct size (A: m x n and B: n x p)


<h2>[Problem 6] Transposition</h2>

In [8]:
e_ndarray = e_ndarray.T
# Now it calculate the product when size of matrix is correctly input
matrix_mul_by_hand(d_ndarray, e_ndarray)

array([[ 46.,  -4.],
       [-34.,  73.]])